export default {
  CLIENT_ID: '7l6s9pq2csob5mb214um7ngcdn',
  USER_POOL_ID: 'eu-west-2_tYDfbmF43',
  REGION: 'eu-west-2',
  csvDownloadLink:
    'https://questionservice-dev-smartcbtcsvbucket-odseew1nbbsm.s3.eu-west-2.amazonaws.com/question_template.csv',
  prod: {
    auth: 'https://o22wcxsgti.execute-api.eu-west-2.amazonaws.com/',
    candidate: 'https://4l2qqa8h3a.execute-api.eu-west-2.amazonaws.com/',
    department: 'https://a6ezqkaqg1.execute-api.eu-west-2.amazonaws.com/',
    faculty: 'https://tnqbtivfr0.execute-api.eu-west-2.amazonaws.com/',
    package: 'https://z99w6kou03.execute-api.eu-west-2.amazonaws.com/',
    institution: 'https://cu6kje541e.execute-api.eu-west-2.amazonaws.com/',
    location: 'https://dttgt7i01l.execute-api.eu-west-2.amazonaws.com/',
    question: 'https://ity4nkks6e.execute-api.eu-west-2.amazonaws.com/',
    test: 'https://vreirdoque.execute-api.eu-west-2.amazonaws.com/',
    testDetails: 'https://hfalf9wxff.execute-api.eu-west-2.amazonaws.com/',
    annex: 'https://3tth647xr1.execute-api.eu-west-2.amazonaws.com/',
    candidateForm: 'https://otj541rsaj.execute-api.eu-west-2.amazonaws.com/',
    CLIENT_ID: '7a70vatuqr10ig301f3kccfnu2',
    USER_POOL_ID: 'eu-west-2_Yvo473E9k',
  },
  dev: {
    auth: 'https://4wyyle8kih.execute-api.eu-west-2.amazonaws.com/',
    candidate: 'https://tgsbr09mpj.execute-api.eu-west-2.amazonaws.com/',
    department: 'https://hqz0q9ceu0.execute-api.eu-west-2.amazonaws.com/',
    faculty: 'https://n336zc0yjl.execute-api.eu-west-2.amazonaws.com/',
    institution: 'https://vo2efvi8hd.execute-api.eu-west-2.amazonaws.com/',
    package: 'https://1lkryb6ci9.execute-api.eu-west-2.amazonaws.com/',
    location: 'https://vi5winmuij.execute-api.eu-west-2.amazonaws.com/',
    question: 'https://2cwt43kx5h.execute-api.eu-west-2.amazonaws.com/',
    test: 'https://4bebsvu80c.execute-api.eu-west-2.amazonaws.com/',
    testDetails: 'https://63epdh3rlj.execute-api.eu-west-2.amazonaws.com/',
    CLIENT_ID: '7l6s9pq2csob5mb214um7ngcdn',
    USER_POOL_ID: 'eu-west-2_tYDfbmF43',
  },
};
